### ISSUE TITLE
ファビコン変更

### ISSUE THREAD

**Issue by AsagaKosho** [tsukuba-shinkan/shinkan-web#10]
大学ロゴは使えないので何らかの何かを用意

**Comment by nandenjin** [comment]
何らかの何か。

**Comment by nandenjin** [comment]
デザインの基幹部分みたいなのはなさそうだったのでブランディングプランとして作りました、部分で使ってくれても見送ってくれても

https://drive.google.com/open?id=1w0E-ZwA8klcpXR5NjFsM0k20KHj1pjSq

![image](https://user-images.githubusercontent.com/7803255/77734660-74587100-704c-11ea-8948-c07047eae819.png)

![image](https://user-images.githubusercontent.com/7803255/77734703-876b4100-704c-11ea-8049-3d9ee274f830.png)

**Comment by AsagaKosho** [comment]
全代会の人がロゴを作ってくれるかも

**Comment by AsagaKosho** [comment]
![新歓web_透過](https://user-images.githubusercontent.com/17997951/78116475-4ce41880-743f-11ea-856b-bda1fcf83f8d.png)
