### ISSUE TITLE
aboutページのスタイリング

### ISSUE THREAD

**Issue by mkobayashime** [tsukuba-shinkan/shinkan-web#101]
aboutページのスタイルは #58 での実装後特に変更されていませんが、
- トップページ/個別ページの背景色が `#eeeeee` に変更されたが、aboutページでは変更されていない
- テキストの `max-width` のようなものが設定されておらず、画面サイズによらず常にスクリーン全幅で表示されるため読みづらい

これらの修正のため
- 背景色 `#ffffff` → `#eeeeee`
- テキスト幅設定(メディアクエリで分岐)

を提案します。問題なければアサインしていただいて構いません。

**Comment by nandenjin** [comment]
@mkobayashime  Cc: @asagatto777 
OK出たのでよろしくお願いしようと思います:pray:

**Comment by mkobayashime** [comment]
@nandenjin 承知しました～
