### ISSUE TITLE
不要なgatsby-imageコンポーネントの削除

### ISSUE THREAD

**Issue by AsagaKosho** [tsukuba-shinkan/shinkan-web#104]
現在、本番用データでビルドを行うと、10000以上もの画像が生成される。
これにともないビルド時間も50分ほどかかっているため短縮が強く求められる。

不要なgatsby-imageコンポーネントを削除することでこの問題を軽減することができる。

現在、Fixed200.js , Fixed180.js は全く使用されていないとみられますが、削除しても問題ないですか？
@yuki-js @nandenjin 

（ #103 のせいでビルドを複数回するはめになり睡眠不足で口調が変ですごめんなさい）

**Comment by nandenjin** [comment]
消すのは構わないと思うんですけどそれでビルド時間縮むんですか……？🤔

**Comment by AsagaKosho** [comment]
@nandenjin 
ローカルで消してみたらめちゃくちゃ縮みました
生成画像数が10000→7000
