### ISSUE TITLE
Google Analytics の追加

### ISSUE THREAD

**Issue by AsagaKosho** [tsukuba-shinkan/shinkan-web#106]
https://www.gatsbyjs.org/docs/adding-analytics/ を利用してGoogle Analyticsを設置する。また、about.js にGoogle Analyticsを使用している旨記載する。

**Comment by yuki-js** [comment]
GAの利用規約とは別に、大学のルールとして大学のHPで利用者情報の収集していいんだっけ？

**Comment by AsagaKosho** [comment]
@yuki-js 
特にルールの存在は聞いたことがない上に、公式サイト www.tsukuba.ac.jp も使ってるから問題ないはずです。
![image](https://user-images.githubusercontent.com/17997951/78654770-050e3700-7900-11ea-86ad-24506b761c21.png)

**Comment by AsagaKosho** [comment]
![image](https://user-images.githubusercontent.com/17997951/78654837-1ce5bb00-7900-11ea-8c64-afb8c8837c73.png)
