### ISSUE TITLE
og:descriptionのカスタマイズ

### ISSUE THREAD

**Issue by nandenjin** [tsukuba-shinkan/shinkan-web#116]
各団体個別ページでOGPがデフォルトテキストになってしまっているので、団体紹介文にするなど対策したいです。

`activityIntroduce`を適当な長さ（200〜300文字くらい or 段落・文などの区切り）で切って入れるので良いのではないかと思います🏃

**Comment by mkobayashime** [comment]
(あっアサインされてないことに今気づいた…すいません…)
