### ISSUE TITLE
og:site_nameの設定

### ISSUE THREAD

**Issue by nandenjin** [tsukuba-shinkan/shinkan-web#117]
現状はタグ自体が存在しません🤔

**Comment by mkobayashime** [comment]
@nandenjin `筑波大学新歓Web`で良いでしょうか。PR投げられます。

**Comment by nandenjin** [comment]
Fw: @asagatto777

**Comment by AsagaKosho** [comment]
Assigned

**Comment by mkobayashime** [comment]
@asagatto777 @nandenjin 現状 `twitter:title` がページタイトルのみですが、`筑波大学新歓Web | ページタイトル` のような形の方が良いのではないかと思います。一緒に修正しませんか。

**Comment by nandenjin** [comment]
いなだ、良いと思います。どっちかっていうとページ固有名称が前のほうが後ろが切れたときにわかりやすいかと思ったのですがどうでしょう

**Comment by mkobayashime** [comment]
確かにそうですね。`ページタイトル | 筑波大学新歓Web` の形でどうでしょう @asagatto777

**Comment by AsagaKosho** [comment]
@mkobayashime 
ページタイトル | 筑波大学新歓Web がいいですね

**Comment by nandenjin** [comment]
Twitterのカードの定義にはサイト名がないのでこの対応でいいと思うんですが、OGP側にはtitleとsitenameが別項目としてあるんですね……`twitter:title`と`og:title`って別の値で実装できる感じですか？

**Comment by mkobayashime** [comment]
@nandenjin できます
![image](https://user-images.githubusercontent.com/17699481/78693738-a2845d80-7936-11ea-98db-c60ba1ca0f03.png)

あと `ogp:title` ではなく `og:title` だと思われます…(他のIssueも同様)

**Comment by AsagaKosho** [comment]
seo.jsに記載あります

**Comment by AsagaKosho** [comment]
seo.js でもろもろいじれます
（限界まで眠たいので今日は寝ますごめんなさい）

**Comment by nandenjin** [comment]
> あと `ogp:title` ではなく `og:title` だと思われます…(他のIssueも同様)

ボケてましたね……すみません直しときます……🙇
