### ISSUE TITLE
モバイルにて横スクロールが可能となっている

### ISSUE THREAD

**Issue by ghost** [tsukuba-shinkan/shinkan-web#120]
#63 に関連している可能性
### 問題点
タブレット・スマホ級サイズの横幅から、横方向にスクロールが可能となっている。
縦方向のスクロールを妨げる要因であり、禁止した方がよいのではないか。

### 解決策
bodyセレクタに対して
`overflow-x:hidden`
を適用

ウィンドウサイズから何らかの要素がはみ出している根本的な原因については不明

**Comment by ghost** [comment]
上記はワークアラウンドなので思い当たる節があればそこを解決してもらう方が良さそうです。（探したけど特定できませんでした...）

**Comment by tkkrr** [comment]
iPhone6/7/8 Plusでの検証ですが，画面幅414pxに対して `<figure>`の幅 222px の2カラムが怪しそうです．

<img width="738" alt="スクリーンショット 2020-04-08 4 01 40" src="https://user-images.githubusercontent.com/36618448/78709067-036b6000-794e-11ea-8d89-49b658b739f2.png">

試しに `src/pages/index.scss`の `$margin-lr: 15px` を `$margin-lr: 10px`に変更して，`<figure>`の幅を212pxにしたら横スクロールできなくなりました．しかし，画像周りのレイアウトがずれる可能性があるので影響を要検証．

**Comment by nandenjin** [comment]
おふたりともありがとうございます！ちなみに @noisyyysion さんの端末情報（OS/ブラウザ/スクリーンサイズ）やスクリーンショットをいただくことは可能ですか？また、あふれているページは`/org/*`の団体個別ページのみですか？

**Comment by ghost** [comment]
![image](https://user-images.githubusercontent.com/16752483/78730655-6d98fa80-7978-11ea-92e0-e81ab62aab47.png)
- iOS13.3.1
- Chrome for iOS
- iPhone XS Max(896x414)

見えづらいですが横スクロールバーが出現しています。
Max OS Chormeでも同様に確認できています。

トップページのみがあふれ、個別のページについては横幅に収まっているようです。

**Comment by noisyyysion** [comment]
**訂正**
端末はiPhone XS Maxになります

**Comment by nandenjin** [comment]
@noisyyysion ありがとうございます🙇‍♂️ 再現したのでこちらで修正かけます！

**Comment by AsagaKosho** [comment]
#126
