### ISSUE TITLE
PC表示時にポスターのhover表示が見切れる

### ISSUE THREAD

**Issue by tkkrr** [tsukuba-shinkan/shinkan-web#126]
Safari, Chromeどちらでも確認．
スクロールバーが二重で表示されている．
#123 のときに追加した `overflow-x:hidden` が影響してそう．

<img width="367" alt="スクリーンショット 2020-04-09 21 59 03" src="https://user-images.githubusercontent.com/36618448/78897569-5ad41200-7aad-11ea-9448-6004f6ac60dd.png">

**Comment by AsagaKosho** [comment]
@tkkrr 一旦、 #123 の変更をもとに戻していただいて、再度 #120 への対応お願いできますでしょうか？

**Comment by tkkrr** [comment]
@asagatto777 わかりました．修正してプルリク投げます．

**Comment by AsagaKosho** [comment]
@tkkrr ありがとうございます！
