### ISSUE TITLE
CIのdeployでlftpの実行に異常な時間を要している

### ISSUE THREAD

**Issue by AsagaKosho** [tsukuba-shinkan/shinkan-web#143]
lftpの実行が2時間以上経っても終了しない。
ファイルの同時転送数の設定等可能か要調査（あるいはファイル転送自体は完了しているがプロセスを終了できていない？）

**Comment by nandenjin** [comment]
SFTPで大量のファイルの転送をやること自体のパフォーマンスがどうなんだという感も出てきたので、

* いったんCIでのデプロイを断念し、ビルド結果を手動で取得できるようにする
* デプロイ操作がCIからも容易なプラットフォームに移す（これはサーバ設定を触れないことにより生じてる他の問題の解決も含む）

の2ステップを踏むのが良いのではないかと思っています
