### ISSUE TITLE
トップページのイニシャルロードが遅い

### ISSUE THREAD

**Issue by AsagaKosho** [tsukuba-shinkan/shinkan-web#144]
![image](https://user-images.githubusercontent.com/17997951/79670302-dd22ab80-81fc-11ea-975b-a97947c91f22.png)
主にJSファイルの読み込みに時間がかかっている模様。

PageSpeedInsightsの結果も非常に悪い
![image](https://user-images.githubusercontent.com/17997951/79670331-0ba08680-81fd-11ea-8ce4-8bc1ef53b923.png)

**Comment by nandenjin** [comment]
`.htaccess`からgzip圧縮有効にできるぽい（`mod_deflate`が入ってるなら）けど、使えるかどうかって試せませんかね

**Comment by AsagaKosho** [comment]
> `.htaccess`からgzip圧縮有効にできるぽい（`mod_deflate`が入ってるなら）けど、使えるかどうかって試せませんかね

この方法はｓｔｂサーバーでmod_deflateが導入されていなかったため負荷でした。
base64でプレースホルダ画像が大量に読み込まれていましたので　Fluid200.js, Fluid700.jsでnobase64に変更したところパフォーマンスの向上が見込めそうです
