### ISSUE TITLE
活動種別ごとの一覧ページを作る

### ISSUE THREAD

**Issue by AsagaKosho** [tsukuba-shinkan/shinkan-web#16]
* 3系（体育系・文化系・芸術系）+その他（一般学生団体など）でそれぞれ表示できるようにする

**Comment by nandenjin** [comment]
画面デザイン案が欲しいです 🙋‍♂

**Comment by nandenjin** [comment]
検索機能 #17 も含め、可能なら別ページというよりはフィルタ表示にする（全部の表示から条件指定して絞っていく）方がUX良い気がしました。

ただし、Gatsbyの仕様上、全団体のデータを読み込んでパフォーマンス的に大丈夫なのか（ページのイニシャルロードが異常に多くなったりしないのか）をよくわかってないので、要リサーチ or ベストプラクティスがわかる人の意見が欲しいです 🤔

**Comment by nandenjin** [comment]
#63 でフィルタ表示でなんとかする方向で進んでいるのでいったんCloseします！またこの方向性で何か議論することがあればお気軽にReopenお願いします:raising_hand_man:
