### ISSUE TITLE
トップページ フィルタ機能の実装

### ISSUE THREAD

**Issue by AsagaKosho** [tsukuba-shinkan/shinkan-web#17]
# Updated

最新の仕様設定は https://github.com/tsukuba-shinkan/shinkan-web/issues/17#issuecomment-609576373 にあります。

---

* ~画面内の配置は[デザイン案](https://xd.adobe.com/view/ca957b4d-3739-4c27-566f-ddd0cf4bead8-bca4/)を対象~
* ~クエリ文字列全体の部分一致を探す~
* ~検索対象カラムは`name` / `activityIntroduce` / `website` / `twitter` / `instagram`~

**Comment by nandenjin** [comment]
デザイン案に検索結果のビューがないのでつけてください 🙏

**Comment by nandenjin** [comment]
フィルタ表示の方がいいんじゃない？って話を https://github.com/tsukuba-shinkan/shinkan-web/issues/16#issuecomment-604920935 に書いています

**Comment by tkkrr** [comment]
- Enter入力で検索する
- 入力に反応して逐次検索を実行する

後者の場合，Lodash.jsのdebounce()を使って，少し遅延させて逐次検索を実装するやり方もあります．
そうすれば全探索でもある程度はブラウザの負荷を減らすことができるかも

参考：
- https://iwb.jp/javascript-throttle-debounce-event-thinning-process/
- https://lodash.com/docs/#debounce

@nandenjin ちなみにフィルタ表示とは，[このサイト](https://www.dell.com/ja-jp/shop/デルのノートパソコン/sc/laptops)のような感じですか？

**Comment by nandenjin** [comment]
> @nandenjin ちなみにフィルタ表示とは，このサイトのような感じですか？

イメージあってます！ @tkkrr 

掲載件数は高々200件くらいのオーダーの予定なので個人的にはインタラクティブな挙動についてはあまり心配していなくて、むしろスクリプト内に200件のデータが素でスクリプトに入ることによるロードパフォーマンスの影響が気になっています。（サイズなどちゃんと計算していないので杞憂かもしれませんが……）

（気にしていないとは言いましたが @tkkrr さんのご提案が普通に考慮すべき有益な内容だったので、実装する方は気にして欲しいと思います:+1:）

**Comment by mkobayashime** [comment]
@nandenjin @asagatto777 僕が議論見逃してたら申し訳ないんですが、フィルタリング(≠検索)の軸は `activityIntroduce` のみの予定ですか?

**Comment by nandenjin** [comment]
@mkobayashime 将来増やすかもしれませんがとりあえずは`activityType`（=体文芸）のみと思ってました（カテゴライズかフィルタかの話だったので）。

他に使える値といえば`organizationType`とかでしょうか？機能提供の気持ちではもっといろいろ作りたいのですが、如何せんこれ以上の値はカラムを足す作業をしないと生まれない感じあります

**Comment by mkobayashime** [comment]
@nandenjin 理解です。それなら体文芸他の4種類で組み合わせが2^4-1(全部オフ除く)=15通りしかありませんし、クライアントのローカルで200個から`activityType`一致するものを探す処理(重そう)をさせなくても、ビルド時にフィルターに一致する要素一覧を15通り全部出力してしまってクライアントにはそれを読ませるだけみたいなこともできそうですね。

**Comment by tkkrr** [comment]
> イメージあってます！ @tkkrr
> 掲載件数は高々200件くらいのオーダーの予定なので個人的にはインタラクティブな挙動についてはあまり心配していなくて、むしろスクリプト内に200件のデータが素でスクリプトに入ることによるロードパフォーマンスの影響が気になっています。（サイズなどちゃんと計算していないので杞憂かもしれませんが……）

@nandenjin 上記確認ありがとうございます．
たしかに右も左も分からない新入生からしてみたらフィルタの方が親切だと思います．しかし，フィルタだけで十分にサークルを絞れるほどの情報量を確保するほうがもしかしたら大変かも？（情報提供するサークルさんも，新歓委も）

初回ロード時の読込み時間についてですが，
- bundleの肥大化が初回読込のパフォーマンスに影響しそう（またそれによる読込時間遅延のブラウザ離脱がこわい）
- 画像がたくさんあるのでとても重そう

あたりが懸念なのかなと思っているのですが（違ったらごめんね），

トップページと検索ページをそれぞれ別ページとして実装すれば，Gatsbyがcode splittingによる最適化をしてくれるので高速化できます（[参考](https://www.gatsbyjs.org/docs/how-code-splitting-works/)）．また，キャッシュも作ってくれるので，2回目以降の読込みからは心配いらないでしょう．
よりカリカリにチューンしたいならimport文の宣言を工夫して，デッドコードの削除，動的モジュール読込を行うと良いです（ただしそこまでの実装はいらないとも思います）．
こんな感じで，Gatsbyで作成している限りは前者の問題は回避できそうです．

後者についても．画像をgatsby-imageによって最適化すれば，遅延読込なり，適切な解像度への変更なりしてくれるので安心かと．

参考までに

**Comment by tkkrr** [comment]
ちなみにfilterが重そうということなので，簡単ですが調査しました．
以下，参考にどうぞ

実行ハードウェアはこちらです．
- Macbook Pro early 2015
- Intel Core i5 デュアルコア 2.7GHz
- RAM 8GB
- SSD 256GB


まず初めに，[こちら](https://uxdaystokyo.com/articles/glossary/response-time-limit/) の記事にあるように，ユーザが許容できる応答までの時間を 100ms ~ 1000ms とします．
青空文庫にある夏目漱石の「こころ」をデータソースとして，1596行（平均 118文字 / 行）の検索をfilterで実装して実行した結果が以下のとおりです．

<img width="778" alt="スクリーンショット 2020-04-02 23 57 48" src="https://user-images.githubusercontent.com/36618448/78269016-fa405480-7543-11ea-8f19-0ed1c6031e47.png">

もちろん1カラムでの検索なので凄く高速です．
それでも，200件5カラムくらいなら余裕そうです．
ただしUIの方はこれよかずっと重くなるのでモッサリするかもしれません．

**Comment by nandenjin** [comment]
# Update

#73 で実装しきれなかった部分をもう一度こちらでまとめておきます……:bow:

## 要件

* 配置、デザイン（案）は以下画像の通り（[XDデザインファイル](https://xd.adobe.com/view/ca957b4d-3739-4c27-566f-ddd0cf4bead8-bca4/)）
* スマートフォンではそれぞれのメニュータップ時に動きがあります
* クエリ文字列全体の部分一致を探索
* 検索対象カラムは`name` / `activityIntroduce` / `website` / `twitter` / `instagram`

## 備考

* 検索バーはヘッダーに置くべきかもしれませんが、 #96 もあるので ひとまずここにしています。

![トップページPC（稲田試験版-ホバー縦型）](https://user-images.githubusercontent.com/7803255/78548853-6240b480-783c-11ea-8050-e846719554ba.png)

![トップページSP（稲田試験版-タップで展開）](https://user-images.githubusercontent.com/7803255/78526097-f21e3880-7813-11ea-9ed0-20c5d54313e6.png)

![トップページSP（稲田試験版-タップで展開-絞り込みモーダル）](https://user-images.githubusercontent.com/7803255/78548816-56ed8900-783c-11ea-94d5-e3c96e43dfc9.png)

![トップページSP（稲田試験版-タップで展開-検索時）](https://user-images.githubusercontent.com/7803255/78526099-f2b6cf00-7813-11ea-8827-6ab97bf3dfb1.png)

**Comment by mkobayashime** [comment]
@nandenjin フィルターUIですが、選択状態の有無にテキスト色しか違いがないのはフィードバックが弱く感じます。幸運にもグレー系の色とつくば紫はP型/D型色覚では共にさほど問題なく判別できるようですが、画面輝度によっては結構判別が難しいのではないでしょうか。

**Comment by nandenjin** [comment]
@mkobayashime 

> 選択状態の有無にテキスト色しか違いがないのはフィードバックが弱く感じます

なんとなくまずい気がするなと思いながらも代案を思い付かずそのままになってました……。とってつけ感ありますがこんなのでどうでしょうか？（角丸枠のなかに角丸枠がいるの気になる人とかいるかな）

![image](https://user-images.githubusercontent.com/7803255/78547193-a4b4c200-7839-11ea-9806-1513ac596c1b.png)
![image](https://user-images.githubusercontent.com/7803255/78547206-aaaaa300-7839-11ea-8db7-26c2f22b9549.png)

**Comment by nandenjin** [comment]
@mkobayashime 

> 選択状態の有無にテキスト色しか違いがないのはフィードバックが弱く感じます。

やばいよなぁと思いながらも代案を思い付けずにいました……こんな感じでどうでしょう？（角丸枠の中に角丸枠がいるの気持ち悪い人いたりするかな……）

![image](https://user-images.githubusercontent.com/7803255/78547688-72579480-783a-11ea-8976-e37d29a47328.png)
![image](https://user-images.githubusercontent.com/7803255/78547729-84d1ce00-783a-11ea-909e-c052c5ff699a.png)

**Comment by mkobayashime** [comment]
@nandenjin 個人的にはそこまで違和感ないですね。良いんじゃないでしょうか。

**Comment by nandenjin** [comment]
ここの未実装が原因で #100 が止まっているのでとりあえず稲田が引き受けて実装しま〜〜す……🚀
