### ISSUE TITLE
画像アセット最適化の実装

### ISSUE THREAD

**Issue by AsagaKosho** [tsukuba-shinkan/shinkan-web#18]
* [gatsby-image](https://www.gatsbyjs.org/packages/gatsby-image/)の導入を念頭に考えています。

**Comment by AsagaKosho** [comment]
@sudame @yuki-js 
お二人のいずれかにお願いしたいのですが、対応可能でしょうか？

**Comment by nandenjin** [comment]
https://github.com/tsukuba-shinkan/shinkan-web/issues/62#issuecomment-607159276 で触れましたが、画像のホスト元について変更を加える必要があるかもしれず、Ownerと協議するので少々お待ちください！

**Comment by nandenjin** [comment]
## Update

[試験公開用データのシート](https://docs.google.com/spreadsheets/d/1r4c4E7r1PDnaf6Mk6YIS6FAOblLBiX66socla-x8ct4)でドライブの画像を使っていた箇所を、試験的に別ドメインに置き換えました。

一応手元で検査はしていますが不具合があればお知らせください！問題なければ、本番用データもこちらに移行する手筈を整えたいと思います。

@yuki-js Cc: @asagatto777

**Comment by yuki-js** [comment]
#64 はマージされましたが閉じますか？

**Comment by AsagaKosho** [comment]
閉じます！
