### ISSUE TITLE
αリリースに向けたContributing Guideの更新

### ISSUE THREAD

**Issue by nandenjin** [tsukuba-shinkan/shinkan-web#20]
他の開発者にもContributeをお願いするにあたって、現状プラス以下の項目はドキュメント化した方がいいと思いました！

* **原稿提出〜サイトデプロイまでのデータフロー**
* **テストデータ、スキーマの詳細**
  * テストデータは適当な画像の寄せ集めである旨
  * どんな情報がどういう形で格納されているか
* **サイトデザインの参照先**
  * XDのリンク？
* **Issueの提出 or 引き受け、PR提出までのフロー**
  * 今あるタスクはどこを参照すればいいのか？どうやって引き受ければ良いのか？
* **以上の項目を参照するためのエントリーポイント**
  * 「ここを見れば得たい情報がわかる」場所（`README` or `CONTRIBUTING`？）

**Comment by asagatto777** [comment]
docsフォルダを作成してその中にドキュメントを格納する

**Comment by nandenjin** [comment]
# ドキュメントファイル振り分け

> 原稿提出〜サイトデプロイまでのデータフロー
> テストデータ、スキーマの詳細

→ [`DATAFLOW.md`](/DATAFLOW.md)（新設）へ

> サイトデザインの参照先

→ [`README.md`](/README.md)へ

> Issueの提出 or 引き受け、PR提出までのフロー

→ [`CONTRIBUTING.md`](/CONTRIBUTING.md) へ

**Comment by AsagaKosho** [comment]
#21 にて対応しました。
