### ISSUE TITLE
consoleへの出力が禁止されていない？

### ISSUE THREAD

**Issue by nandenjin** [tsukuba-shinkan/shinkan-web#31]
[`eslintrc`](https://github.com/tsukuba-shinkan/shinkan-web/blob/dev/.eslintrc.js)で`no-console`が指定されておらず、`console.log`などの出力を消し忘れたままでもLintが通ってしまう。

**Comment by AsagaKosho** [comment]
@nandenjin 
よろしくお願いいたします。

**Comment by nandenjin** [comment]
https://github.com/tsukuba-shinkan/shinkan-web/pull/64#discussion_r402246465 で問題になっている `eqeqeq` などもこの機会に再設定すべきではないかという気持ちがあります
