### ISSUE TITLE
スマホ向けレイアウト

### ISSUE THREAD

**Issue by yuki-js** [tsukuba-shinkan/shinkan-web#36]
iPhoneでは以下ような表示になり、本文が読みにくいため、画面幅に依らないレイアウトまたはレスポンシブデザインにする
![image](https://user-images.githubusercontent.com/20838151/77852140-e4ffb900-7217-11ea-8618-262f6dcf62a5.png)

**Comment by AsagaKosho** [comment]
@yuki-js 
ありがとうございます。
一定幅以下でワンカラムに切り替えようと思っていたのですが、何pxで切り替えるようにするのが妥当ですかね…？
一般的な768pxだとポスター画像が大きくなりすぎてしまうような気もしており

**Comment by yuki-js** [comment]
大きさはmax-widthを設定すれば良い。
フォント設定によっては切り替え境界は768pxでも狭いかもしれない。

**Comment by nandenjin** [comment]
#53 #63 など各ページごとで対応が始まっているのでこちらはいったんクローズします！何かありましたらお気軽にReOpen願います:pray:
