### ISSUE TITLE
トップページUIの改善提案

### ISSUE THREAD

**Issue by mkobayashime** [tsukuba-shinkan/shinkan-web#42]
現状トップページでは体育系/文化系などのカテゴライズの上、それぞれが横スクロール可能な領域としてデザインされていますが、このUIには課題が多いと感じます。
これを再考していただきたいというのが趣旨です。

1. サークルを探す新入生は、初めから特定のカテゴリに絞って探しているとは限らない
1. PCからアクセスした際、マウススクロールでは横スクロールができない
1. そもそもポスターの画像は一見して情報が伝わりやすいオブジェクトではなく、一覧表示してもサークルを探す手助けになるとは考えづらい

### 1. について
デフォルトでは全サークルを表示させ、必要に応じてカテゴリーでフィルタリングできるUIの方が自然かなあと思います。XDでとりあえず組んでみたイメージです。
![iPhone X-XS-11 Pro – 1](https://user-images.githubusercontent.com/17699481/77854297-7117dd80-7224-11ea-83ad-57318b429b8f.png)

### 2. について
チルトシフトのないマウスではスクロールバーのドラッグ以外にスクロールする術がないため、順番にサークルを見て探す際にはかなり不自然な操作になってしまうと思われます。
メディアクエリを見て、PC判定の場合はスクロールイベントをpreventDefaultして横スクロールさせることで、マウススクロールでも横スクロールができるような実装が必要ではないかと思います。

### 3. について
かなり根本的な変更提案となってしまいますが、そもそもトップページに表示すべきはポスター画像ではなくサークル名のみなのではないかと思います。
トップページはサークルを一覧するためのものであり、単体でスペースを専有するポスター画像はその一覧性を大きく落とすものです。
ポスターに掲載されている内容は個別サークルの詳細情報として個別ページで見られる状態にすべきではないでしょうか。
こちらもXDで組んでみたイメージです。
![iPhone X-XS-11 Pro – 2](https://user-images.githubusercontent.com/17699481/77854470-88a39600-7225-11ea-9599-716e6dfee454.png)

---

ご検討ください。
念のためXDのリンクも置いておきます。
https://xd.adobe.com/view/e0d2fcbd-5ecd-4f97-56e5-6649628f28ad-96e3/

**Comment by AsagaKosho** [comment]
@mkobayashime
ありがとうございます。
設立趣旨がポスター掲示板の代替という観点からポスター画像の一覧表示にこだわっていましたが再考してみます。

**Comment by nandenjin** [comment]
Ref: https://github.com/tsukuba-shinkan/shinkan-web/issues/16#issuecomment-604920935 （フィルタにした方がいいんじゃねって話）

**Comment by nandenjin** [comment]
ポスター画像がスペースを占有気味（`トップページはサークルを一覧するためのものであり、単体でスペースを専有するポスター画像はその一覧性を大きく落とすものです。`）だというのは稲田も思っていることですが、ビジュアル的に各団体の個性が出るポイントでもあり、完全に抜いてしまうのは惜しいなあと悩んでいるところです。

ただ、ポスターのコンテンツはそもそもA4判での印刷を前提として組まれており、コンテンツの可読性の度合いはデバイスによって異なる&技術的にそのあたりを判別するのは難しいだろうと思われるので、ポスター画像を表示させるにしてもテキストでの併記は必須ではないかと思います……（この話は単体で https://github.com/tsukuba-shinkan/shinkan-web/issues/28 にも載せています）

**Comment by mkobayashime** [comment]
ありがとうございます。
#28 は拝見していたのですが、フィルターが #16 で提案されているのは見落としておりました。重複気味の Issue で申し訳ありません…

ポスター画像についてですが、どの程度個性が出てどの程度トップページに求められるものかが、結局のところ過去に見たことがない新入生の私にはわかりませんので、判断はお任せします。

また、ポスター画像の表示有無に関わらず横スクロールはあまり適していないのではないかと思うのですが、原案デザイン時に何か横スクロールによって意図したことはありますか?

**Comment by nandenjin** [comment]
@mkobayashime 

> 原案デザイン時に何か横スクロールによって意図したことはありますか?

デザインは今回 @asagatto777 が全部担当してて稲田はノータッチなんですが、個人的には上下左右どっちにもフリーに動くのは端的にややこしいかなという気がしたので、左右スクロール入れるなら後々JSでコントロールする（ドラッグして動かすようにするとか、ボタン操作にするとか）ようにした方がいいのかなと思ってます。横方向にネイティブのスクロールバー出てるのもアレですし……

横に並ぶ枚数にもよりますね、あまり多いと横スクロール自体がだるくなってくるのでそれなら操作自体を再考したほうがいいかもです:thinking: （@asagatto777 どうなんですっけこれ）

**Comment by AsagaKosho** [comment]
挙動自体は[Amazon Prime Video](https://www.amazon.co.jp/Amazon-Video/b/?ie=UTF8&node=2351649051&ref_=nav_cs_prime_video)がいい感じだなぁと思って採用しました。
（トラックパッドで動かしていましたがよく考えたらデスクトップPCにトラックパッドはないですね…ごめんなさい）
枚数は各60枚（その他は10枚以下）程度になると思われるのでたしかに不適切な設計であったと思います。

**Comment by nandenjin** [comment]
自分でもデザイン書いてみていろいろ考えることがあったので、参考までに共有します。

データは公式のXDの隅っこに入れています: https://xd.adobe.com/view/ca957b4d-3739-4c27-566f-ddd0cf4bead8-bca4/

## Plan A（縦型モーダル）

@asagatto777 が言及していたAmazon Prime Videoそのままのデザイン。PCはマウスホバーで詳細モーダルが展開、クリックで個別ページへ遷移。スマホはタップで画像をモーダルに置き換え、再タップで遷移。

* 👍 展開モーダルで他のポスターが（そこまで）隠れない
* 👎 モーダル内の折り返し幅が狭いのであまり多くのコンテンツは入れられなさそう（ただし、デザインではフォントサイズが大きめなのでもう少し入れることもできそうです）
* 💡 初期状態ではポスターがびっしり並んでる方が綺麗だけど、そこにテキスト情報をどう補完するかが考え所という感じ。
* 💡 PCではホバーで表示でストレスではないものの、スマホではいちいちタップしないとテキストが読めないのは微妙かもしれない
* 💡 PCで横スクロールは入れなくてもなんとかなるかな？一方で、スマートフォンでのデザインを見ていると、並ぶコンテンツが縦型のポスターであるがゆえ、横スクロールも案外効率的な働きをしそうだなという気持ちになりました:thinking:

![トップページPC（稲田試験版-ホバー縦型）](https://user-images.githubusercontent.com/7803255/77981974-2e4e2680-7346-11ea-8562-beec3ae987a9.png)

![トップページSP（稲田試験版-タップで展開）](https://user-images.githubusercontent.com/7803255/77982054-52116c80-7346-11ea-97c7-fc7588a643d2.png)


## Plan B（横型モーダル）

一番ありそうなデザイン。Aの折り返し幅問題を解決する。PCの挙動は先ほどと同じ、スマホはデザインも含めて同一で良いかな？という感じ

* 👍 モーダル内が窮屈でなくて良い
* 👎 モーダルで他のコンテンツが大きく隠れてしまう。
  * モーダルにマウスを載せることはできない（載せようとするとその背後のコンテンツのモーダルを開く）仕様にすれば解決しそうだけど、どのみちグリッドに大きなタイルを被せるビジュアルが邪魔な感じはある
* 🤔 そもそもモーダルにはどの程度まで文章を表示するのが良いのか？

![トップページPC（稲田試験版-ホバー横型）](https://user-images.githubusercontent.com/7803255/77982933-884feb80-7348-11ea-8cb6-69d8d2b61577.png)

## Plan C（マップ型）

スクロールの方向の制約をなくせばもっといろいろできるんじゃないのか？という思いつきです。

* ポスターを散らしたワールドをドラッグ操作で拡大縮小・移動できるようにする。
* PCはホバーでモーダルを展開・クリックで遷移
* スマホはタップで団体名をチップ表示、再タップで遷移

PCホバーの感覚は[1000 Chrome Experiments](http://1000.chromeexperiments.com/)とかを思い浮かべています。

* 👍 ポスターのサイズ・レイアウトを自由に動かせる
* 👍 スクロールのUIを気にしなくて良い
* 👎 実装や動作の担保が面倒そう
* 👎 独特な操作になるので何かしらガイドが必要になる場合がある（かもしれない）

個人的にはそれなりに気に入ってるんですが、こういうプロジェクトに投入するにはお遊びのようで若干ハードル高いかもなという気持ち。キモは複数あって分割可能なので、レイアウト自体はAやBのままでも、拡大縮小とか攻めたインタラクティブ性の概念を入れられれば……みたいな意図です。

![トップページPC（稲田試験版-マップエクスプローラー）](https://user-images.githubusercontent.com/7803255/77983167-3a87b300-7349-11ea-9600-6c48aa940e58.png)
![トップページPC（稲田試験版-マップエクスプローラー） – ホバーorクリック](https://user-images.githubusercontent.com/7803255/77983466-15e00b00-734a-11ea-8706-d9c6c78ce209.png)
![トップページSP（稲田試験版-マップエクスプローラー）](https://user-images.githubusercontent.com/7803255/77983487-242e2700-734a-11ea-9f0f-48f6444b8d0b.png)
![トップページSP（稲田試験版-マップエクスプローラー） – タップ](https://user-images.githubusercontent.com/7803255/77983480-20020980-734a-11ea-8ae1-5f5ef022aa5a.png)

検討過程で好き放題やってしまいましたが、スクロールの方法、テキスト情報の出し方など、どこかで取り入れるヒントになれば幸いです:bow:

**Comment by mkobayashime** [comment]
3プランに共通するのですが、ポスターの(おそらく)ほとんどは画面に複数表示させられるような小さなサイズでビジュアルだけを見ても大して情報が得られないものである以上、1回クリックやホバーしないとサークル名や詳細が表示されないというのがそもそもアンチパターンなのではないかと思っています…。モックのように小サイズでも十分それぞれの情報が見て取れる写真というメディアを並べる場合にはこれで良いかもしれませんが、今回のシステムではせめてサークル名ははじめから全サークル表示させるべきではないでしょうか? (このサイズではポスターに記載されているサークル名が読み取れないだろうということを前提にしています)

Plan C はジェスチャーの実装が若干面倒そうではありますが、僕もレイアウトとしては割と良いと思います。個人的には watchOS のホーム画面をイメージしているんですが、ポスターを何を基準にどう並べるかが難しいかもしれないですね(他の案でもただのあいうえお順で良いのかという問題はある)。

同じく Plan C のモバイルでフィルタリングが画面下部にあるのは非常に良いと思います。この Issue のはじめの僕の案では上部でしたが、画面サイズと指の届く範囲を考えるとここにしない理由がないですね。

**Comment by nandenjin** [comment]
@mkobayashime 
対応遅くなりすみません:bow: 

> 1回クリックやホバーしないとサークル名や詳細が表示されないというのがそもそもアンチパターンなのではないか

そうなんですよね……元々自分が #28 で言及したことでもあるので、ホバーアクションなしのデザインも同時に試作してみていたのですが、やっぱりどう頑張ってもちょっと疎なイメージになるかなと感じています。（実際の使い勝手も見てみたいので、手が空いたらどれかの案で試作もしてみたいと思います。）

他の方でも良いので、（サークル名表示をした状態での）いい案あれば聞きたいです。

![トップページPC（稲田試験版-ホバーなし）](https://user-images.githubusercontent.com/7803255/78095907-332cdc00-7413-11ea-88aa-badfae9453e0.png)

![トップページPC（稲田試験版-ホバーなし縦型）](https://user-images.githubusercontent.com/7803255/78096090-b8b08c00-7413-11ea-9f6b-d163f613b46c.png)

 > ポスターを何を基準にどう並べるかが難しいかもしれないですね

おっしゃる通り、他の案も含めて懸案であると思います。50音順は探しやすさはありますが、毎回同じ団体が目につきやすいのと、そもそも読み仮名登録してないのでそこからになりますね。 @asagatto777 何か計画してたことあったりしました……？

（下手に優劣をつけるわけにもいかないですし、検索やインタラクティブソートができるなら毎回ランダムでもいいのかなと思ったり……）

**Comment by AsagaKosho** [comment]
データの取得は仕様上入力順が一番楽だなあということでそうしていましたが、どうすべきか。。。

**Comment by AsagaKosho** [comment]
ちなみにヘッダーデザインの大幅な変更は広報室手続き的にめんどくさいです

**Comment by AsagaKosho** [comment]
僕の思想としては、ポスターには基本的に見やすい形で団体名が記載されていることから、文字で併記することは必要ないと考えています。（ホバーでの表示はあってもよい）
あくまで、「掲示板の代替」というコンセプトであるためポスターの一覧を主軸にするという方針は変更なしでお願いします

**Comment by AsagaKosho** [comment]
今考えた案では
トップページ　　　　　→各活動種別一覧ページへのリンク
各活動種別一覧ページ（ #16 参照）　→そこに該当する団体のポスター一覧をすべて表示（横スクロールは廃止）
が最適かなと思っています。

**Comment by AsagaKosho** [comment]
@mkobayashime さんの
> サークルを探す新入生は、初めから特定のカテゴリに絞って探しているとは限らない

とのことですが、すべてを一覧表示すると膨大な件数（200以上）になってしまうため余計に探しづらくカテゴリー別の表示が妥当だと考えます。

**Comment by AsagaKosho** [comment]
各活動種別一覧ページにおいては @nandenjin さんのPlanAを採用します。
（独断で申し訳ございませんが、公開までの日時が迫っているためご了承ください。）

**Comment by AsagaKosho** [comment]
ごめんなさい一部読み飛ばしていたので再検討します

**Comment by nandenjin** [comment]
@asagatto777 

> すべてを一覧表示すると膨大な件数（200以上）になってしまうため余計に探しづらくカテゴリー別の表示が妥当だと考えます。

（そのまま使うことだけを前提にするのではなくて「トップページ内でフィルタ表示が可能なようにすれば解決する」という提案であって、その議論をしていたのではなかったんです……？）

---

なるべく早く＆期限に合うように公開しなきゃいけないという重要性は全然わかるのでいったん実装に移るのは良いと思うのですが、それを理由に提案いただいたことや議論したことを吹っ飛ばすのは勿体ないので、他に支障が出なければ引き続き改善を検討したいです。

サイト自体は今後1ヶ月以上のスパンで稼働する可能性があるので、ここではいったんClose、タイミングを見てReopenするなどすれば良いのではないかと思います🤔（Openのまま残してても全然良いですが）

**Comment by nandenjin** [comment]
このまま実装に移るなら別Issue立てますがいかがです？

**Comment by mkobayashime** [comment]
活動種別ごとのページにするにせよ全表示でフィルタリングを実装するにせよ Plan A のレイアウトなのは同じなので、とりあえず現行のトップページのレイアウトを Plan A に変更する Issue を建てるのはどうでしょう?

**Comment by AsagaKosho** [comment]
@nandenjin @mkobayashime 
その方向性で別Issueお願いします

**Comment by AsagaKosho** [comment]
フィルタリングに関しては @nandenjin さんのPlanCベースに実装お願いしてもよろしいでしょうか？

**Comment by nandenjin** [comment]
@asagatto777 

立てました 🙆‍♂問題なければこちらはいったんCloseお願いします。まだコメント返すならそのままでOKです。
