### ISSUE TITLE
スタイルシートの切り分けがほしい

### ISSUE THREAD

**Issue by nandenjin** [tsukuba-shinkan/shinkan-web#44]
全てのスタイルシートが[`global.css`](/src/styles/global.css)に書かれている状態ですが、このまま進めるとこのファイルが肥大し見通しが悪くなるのが明らかなため、ページまたはコンポーネントごとに名前空間を作って切り分けることを提案します。

**Comment by nandenjin** [comment]
あ、ごめんなさい送ってから[`layout.css`](/src/components/layout.css)の存在に気づきましたが、なんだこれは？テンプレートのデフォルトかな……？

**Comment by mkobayashime** [comment]
`layout.css`(現`layout.scss`)はイニシャルコミット f49a21072d627bcfa80602f9ac3a4ff2ed9a8552 の後SCSSへのリネーム以外で改変がないため、テンプレートデフォルトのリセットCSS的なものと考えて良いんじゃないでしょうか。基本的には手で触る必要はないと思います。

スタイルの切り分けについてですが、本件 @nandenjin さんのローカルで進展ありますでしょうか?
特に進んでないのであれば、共通化されたコンポーネントの標準スタイルを全てSCSSのMixinで定義し、各ページごとに切ったSCSSファイルから`@include`するのはどうでしょうか。以下多少具体的に例示します。

ディレクトリ
```
src/
└ styles/
　├ mixins/
　│└ mixin.scss
　└ pages/
　　├ top.scss
　　├ circle.scss
　　└ about.scss
```

`mixins.scss`
```
@mixin h2 {
    font-size: 12px;
    font-weight: 700;
}
```

`top.scss`
```
@import '../mixins/mixin.scss'

.categories {
    .scrollList {
        .scrollItem {
            .circleName {
                @include h2;
                margin-bottom: 20px;
            }
        }
    }
}
```

**Comment by nandenjin** [comment]
@mkobayashime 

> テンプレートデフォルトのリセットCSS的なものと考えて良いんじゃないでしょうか

あ、ありがとうございます:pray: @asagatto777 にも確認とってテンプレについてきたリセットCSSであることを確認してました

> 本件 @nandenjin さんのローカルで進展ありますでしょうか?

稲田は今何も着手してません！フロントを主導してる @asagatto777 曰く、Gatsbyにスタイルの典型作法的なモノがないのか確認したくてリサーチ中⏳とのことです。ただ、軽く直に協議してみた感じでは、

* このプロジェクト程度の規模であれば、できるだけ複雑な仕掛けを減らして、誰にでも扱いやすい形にしたい

具体的には、

* リセット、基本スタイルはグローバルに定義する
* コンポーネント、ページには個別に定義（名前空間の定義はBEMなどで対処）
* 個別のスタイルシートファイルの間には可能な限り関連性を持たせない（「存在を知らないと正しく書けない」をできるだけ減らす）

みたいな方向性を作るのが良いのではないかな〜という話になってました。ご意見あればお聞きしたいです:pray:

**Comment by mkobayashime** [comment]
>あ、ありがとうございます🙏 @asagatto777 にも確認とってテンプレについてきたリセットCSSであることを確認してました

良かったです。触る必要はないと思っていたんですが、このファイルが複数セレクタ(h1~h6など)に対して`font-family`を指定しており、そのせいで`global.scss`で全称セレクタに記述している`Noto Sans JP`がオーバーライドされてしまっているので、この部分は消したほうが良いかもしれません。別にIssueを建てます。

>稲田は今何も着手してません！フロントを主導してる @asagatto777 曰く、Gatsbyにスタイルの典型作法的なモノがないのか確認したくてリサーチ中⏳とのことです。ただ、軽く直に協議してみた感じでは、
>︙
>みたいな方向性を作るのが良いのではないかな〜という話になってました。ご意見あればお聞きしたいです🙏

規模が大きくないのでシンプルな構造にしたいというのは全面的に同意です。基本的にはその方針で行きましょう(Gatsbyのお作法的なものが見つかった場合にはそちらで)。

> - リセット、基本スタイルはグローバルに定義する
> - コンポーネント、ページには個別に定義（名前空間の定義はBEMなどで対処）
> - 個別のスタイルシートファイルの間には可能な限り関連性を持たせない（「存在を知らないと正しく書けない」をできるだけ減らす）

このあたりも承知しました。
「存在を知らないと正しく書けない」ものについてですが、
 - 色変数をまとめるファイル
- ブレークポイント及びメディアクエリ用のMixinをまとめるファイル

あたりは最低限必要かなあと思います。いかがでしょう?

**Comment by nandenjin** [comment]
@mkobayashime 

`layout.scss`の件について、Issue確認しましたありがとうございます:+1:

> * 色変数をまとめるファイル
> * ブレークポイント及びメディアクエリ用のMixinをまとめるファイル
> あたりは最低限必要かなあと思います。いかがでしょう?

稲田個人でもだいたいのケースでそれは作ってるので同意です:ok: 

 @asagatto777 

特にこれ以上進行がないようであればジャッジGoとアサインお願いして良いですか？:pray:

（ブレークポイント作るなら結局どの辺にするんだっけ……）

**Comment by mkobayashime** [comment]
ブレークポイント、そもそもいくつにしましょう?
