### ISSUE TITLE
font-familyの記述散逸の解消

### ISSUE THREAD

**Issue by mkobayashime** [tsukuba-shinkan/shinkan-web#51]
`global.scss`の冒頭で`Noto Sans JP`がGoogle Fontsからインポートされており、全称セレクタに`font-family: 'Noto Sans JP', sans-serif;`が指定されていますので、基本的にはサイト内の全テキストを`Noto Sans JP`に統一する意図があるのだと思います。
しかし現状トップページ/サークル個別ページの多くのテキストにはNotoが当たっておらず、`sans-serif`にフォールバックされています。
これは`layout.scss`が`h1~h6`などの(全称セレクタより優先度の高い)セレクタに`font-family`を指定しているためであり、不要(というか邪魔)な記述なため削るべきではないかと思います。

**Comment by mkobayashime** [comment]
僕にアサインしていただいて構いません。

**Comment by AsagaKosho** [comment]
@mkobayashime 
ご連絡遅くなって申し訳ございません、Assignさせていただきます！
よろしくお願いいたします。

**Comment by nandenjin** [comment]
@asagatto777 

Issueの本義から外れるんですけど、`layout.scss`、テンプレートデフォルトのCSSでおそらく全容を把握している人がおらんと思うので、この機会に整理を議論しませんか🤔 リセットCSSというにはあまりに手が混みすぎてるし、こういう風に`global.scss`を上書きする立場にいるのいただけないと思うので……別Issue立ててこの件が落ち着いてから対処する方が良いかな……:thinking:

**Comment by mkobayashime** [comment]
リセットCSSの割にお行儀が悪いというのは本当にそうだと思うので、メジャーなリセットCSS探してきて丸ごと入れ替えるだけでも良いような気がしますね

**Comment by mkobayashime** [comment]
[normalize.css](https://github.com/necolas/normalize.css/blob/master/normalize.css) あたりがリセットCSSとしてはちょうど良いかなと思っているんですが、いかがでしょう?
何もかもリセットするというよりは、最低限必要なところ(ブラウザ周りの`margin`など)だけリセットする思想のものです。もちろん`font-family`などには触っていません。

**Comment by mkobayashime** [comment]
リセットCSSを入れ替える方向で問題ないかと思いますので、こちらは閉じて新たにIssueを建てます
