### ISSUE TITLE
SCSSファイルへのスタイル記述集約

### ISSUE THREAD

**Issue by mkobayashime** [tsukuba-shinkan/shinkan-web#52]
現状スタイルがjsx内にも`style={{}}`の形で各所に記述されています。

例: https://github.com/tsukuba-shinkan/shinkan-web/blob/db0315ca656ff4fe616dd873f2c1e3572b114748/src/components/layout.js#L29-L35

メンテコストを考えるとスタイルは全てスタイルシートに記述されているべきですので、これらをSCSSファイル(スタイルシート)内の当該箇所に移動することを提案します。

**Comment by AsagaKosho** [comment]
@mkobayashime 
こちらに関してもAssignさせていただきます。よろしくお願いいたします。

**Comment by yuki-js** [comment]
Styled ComponentなどのCSS埋め込みライブラリ(?)を使うといいと思います。
Styled Componentなら、HTML要素にCSSをバインドしたコンポーネントを作れ、Gatsbyにプラグインを入れるだけで使えます。 #44 でもCSSの書き方に関しては議論してますが、本IssueのようなものであればStyled Componentのほうがわかりやすいと思います。ただ、Styled Componentは肥大化しがちだったり、若干慣れやエディタの配慮が必要なので、併用も全くアリ。

**Comment by mkobayashime** [comment]
@yuki-js
ありがとうございます。
僕個人 Styled Components に類するものは書きなれており好きなのですが、#44 にてプロジェクト規模が小さいことから BEM で十分かなという話が出ている通り、今回の用途には若干オーバースペックかなという気がしています
