### ISSUE TITLE
個別ページUIの作成

### ISSUE THREAD

**Issue by HikaruEgashira** [tsukuba-shinkan/shinkan-web#53]
## 概要

はじめまして、
@asagatto777 さんのUI作成に合わせたほうがいいかもしれませんが、提案も兼ねてサークル紹介ページ（単体ページ?）のデザイン案を作成しました。説明用なのでこのデザインは使わなくてもいいです。

![image](https://user-images.githubusercontent.com/39324739/77931909-c79a2000-72e7-11ea-89d2-82e6cb8e4a61.png)

## 変更点

- デスクトップにて一画面表示にする必要はないと思いました。なぜなら、ポスターとほぼ同じ内容が並列に表示されているとかえって見にくくなると思うからと、webなら縦スライドを中心のデザインが向いていると考えられるからです。
- なので、flex表示を縦方向に変更しました。
- 外部へのリンクはコンテンツ末尾のほうが、UXが高いと思います。（普通なら説明をすべて読んだ後にクリックするため）
- 活動種別を追加
- imageUrlsが複数ある場合に対応

その他のデザイン(画像ダウンロードやシェアボタン)は仮置きなので、ご意見お願いします。
ちなみに参考はdribbble.comです。

## 触るファイル

`src/templates/PostTemplate.js`
どこかしらにscssファイルを生成する。
コンポネントを生成する可能性も。

## 備考

デザインが確定後、自分にアサインしてもらっても大丈夫です。
今回Xd環境が身近になかったので、figmaで作成しました。（すみません）
https://www.figma.com/file/UlWwvkECgva55Y4Qm3yrQA/web_shinkan_ehika?node-id=7%3A29

**Comment by AsagaKosho** [comment]
@HikaruEgashira 
確認させていただきました。デザイン案ありがとうございます。
本日中に検討させていただいてまたご連絡させていただきます。

**Comment by nandenjin** [comment]
@HikaruEgashira 

お手伝いでメンテナーをしている稲田です🙋‍♂️ フロントの主担当ではないのですが、個人的に気になった点を質問させてください。

> デスクトップにて一画面表示にする必要はない

これについて、もう少し詳しくお伺いできますでしょうか？:thinking: スクロールしないで読める範囲内に無理に全てを収める必要がないのはもちろんだと思いますが、添付いただいている画像だと、テキスト情報を読むためにはほぼ確実にスクロール動作を強要することになりそうです。また、PCビューではポスター画像がビューポートに収まっておらず、却って見辛いように思われます。

> ポスターとほぼ同じ内容が並列に表示されているとかえって見にくくなる

これについても、もう少しお聞きできますでしょうか？「ポスターとテキストのコンテンツは似通っており、横並びにするのは冗長である」ということでしょうか？

どうぞよろしくお願いします:bow:

**Comment by nandenjin** [comment]
あともう一点、画像のアスペクト比に自由度を持たせておられるようだったのでもしかしたら伝え切れてないのかもと思ったのですが、[Dataflow Documentのスキーマ](https://github.com/tsukuba-shinkan/shinkan-web/tree/dev/DATAFLOW.md#-スプレッドシートのスキーマ)にあるように、`imageUrls`のリソースはアスペクト比自由ですが、`posterImageUrls`のリソースは「A4縦判のアスペクト比」であることとしているので、少なくとも`posterImageUrls`の表示は縦位置のアスペクト比で最適化できそうです（ @asagatto777 と @nandenjin はその方向で設計していました）。

きちんと読み取っておられた上でのデザインでしたらすみません……（このドキュメントを書いたのも稲田なので、伝わりにくい点があったらご指摘ください……）

**Comment by nandenjin** [comment]
Ref: #9

**Comment by HikaruEgashira** [comment]
@nandenjin 
ご確認ありがとうございます。

> PCビューではポスター画像がビューポートに収まっておらず、却って見辛いように思われます。

ラフ案では画像の縦幅を考慮に入れてませんでした。申し訳ないです。
ポスター自体は1画面で見えるようにしたほうがいいと思います。

> ポスターとテキストのコンテンツは似通っており、横並びにするのは冗長である

そういう意味です。サークルのポスター制作に携わった身としては、伝えたいことを纏めたものがポスターであるため、説明のような詳しい内容は画像コンテンツと分かれているべきだと思いました。

**Comment by HikaruEgashira** [comment]
画像の背景をグレーにしているのは、ポスターの背景が白だと、境界が分かりにくかったからです。
あと画像のアスペクト比に自由度を持たせたというよりは、レスポンシブなUIを重視した感じでした。

アスペクト比を考慮して縦並びにしているという方向性までは把握できてなかったです。
スマホでの表示のデザインによっては、現状の設計でもよいと思われます。

**Comment by nandenjin** [comment]
@HikaruEgashira 
対応遅くなってしまってすみません……！:bow:

> 伝えたいことを纏めたものがポスターであるため、説明のような詳しい内容は画像コンテンツと分かれているべき

こちらですが、個人的には

* ポスターデザインではぱっと目に入ることを重視して要素の配置や絞り込みをする
  * （詳しい内容はビラやWebサイトなど別の場所で届ける）

ものだと考えていたので、テキストの解説とは別物として扱うべきだという思想で進めていました（※デザイナーは稲田ではないのでまた別の考えがあるかもです）。人それぞれですね……:thinking: 

---

提供いただいたデザインをフォークして、

* PCビュー・スマートフォンビューで画像の縦幅がビューポートにフイットするよう調整
* 両ビューでのヘッダー・フォントのサイズを見かけ上同じに調整

したレイアウトデザインを作成してみました（[Figma](https://www.figma.com/file/fRjWqCWgsjMqlYOnUiRuhs/shinkan-web-issue-53)）。

ファーストビューが縦型のポスターであることは保証されるとすると、PCビューでの画像左右の大きな空白は少し気になります。また、

> 外部へのリンクはコンテンツ末尾のほうが、UXが高いと思います

についても、できるだけスクロールを発生させずにユーザーアクションを網羅するに越したことはないので、複数置いても良い要素はページ上部にも残しておく方が良いと感じました。

現行デザインのレイアウトのままになるにしても、この部分は取り入れて、ページ下部にリンクを増やす対応をしたいですね……！

![image](https://user-images.githubusercontent.com/7803255/78105318-ddb0f900-742b-11ea-96a0-d84746d88700.png)

**Comment by nandenjin** [comment]
@asagatto777 フロント担当、意見をください 🙋‍♂

**Comment by AsagaKosho** [comment]
@nandenjin @HikaruEgashira 

> > 伝えたいことを纏めたものがポスターであるため、説明のような詳しい内容は画像コンテンツと分かれているべき

> 
> こちらですが、個人的には
> 
> ポスターデザインではぱっと目に入ることを重視して要素の配置や絞り込みをする
> （詳しい内容はビラやWebサイトなど別の場所で届ける）
> ものだと考えていたので、テキストの解説とは別物として扱うべきだという思想で進めていました（※デザイナーは稲田ではないのでまた別の考えがあるかもです）。人それぞれですね……🤔

私もこれと同じ考えです。スクロールなしですべての情報にアクセスできることを重きに置いていました。（ソーシャルリンクに関しても同様です。）

**Comment by AsagaKosho** [comment]
@nandenjin 
上を踏まえてもう一度プロトタイプお願いできますか？
お手数をおかけします

**Comment by nandenjin** [comment]
すみません遅くなりました！こんな感じでいかがでしょうか 

* スクロールなしでも可能な限り多くの情報が画面に入る
* 縦型のポスター画像のアスペクト比は固定なのでその部分は最適化、他の画像はモーダル表示
* 外部へのリンクを挿入箇所を増やしました

🧰XDデザインファイル：https://xd.adobe.com/view/ca957b4d-3739-4c27-566f-ddd0cf4bead8-bca4/

@asagatto777 

![個別ページ（PC）](https://user-images.githubusercontent.com/7803255/78419140-afc2f300-767d-11ea-9220-e0c4c45967dc.png)
![個別ページ（PC・画像モーダル）](https://user-images.githubusercontent.com/7803255/78419143-b3567a00-767d-11ea-940c-6455ccae5f3c.png)
![個別ページ（スマホ）](https://user-images.githubusercontent.com/7803255/78419145-b6ea0100-767d-11ea-941c-9f5721c0afcc.png)
![個別ページ（スマホ・画像モーダル）](https://user-images.githubusercontent.com/7803255/78419146-ba7d8800-767d-11ea-9082-282e2d6cc8a8.png)

**Comment by AsagaKosho** [comment]
@nandenjin 
Great! ありがとうございます！ 👍

**Comment by AsagaKosho** [comment]
@nandenjin 実装お願いします！

**Comment by nandenjin** [comment]
@asagatto777 

[![](https://img.gifmagazine.net/gifmagazine/images/1588660/original.gif)](https://gifmagazine.net/post_images/1588660)
