### ISSUE TITLE
floatをflexboxに置き換え

### ISSUE THREAD

**Issue by mkobayashime** [tsukuba-shinkan/shinkan-web#56]
現在横並びレイアウトの多くが`float`で記述されていますが、レンダリングパフォーマンスは圧倒的に`flexbox`の方が良好([出典](https://ics.media/entry/11459/))であり、解除の手間がないこと、デザイン案に沿ってピクセルパーフェクトを目指しているわけではないことなどを考えると`flexbox`に置き換えるべきではないかと思います。
ブラウザサポートも問題ないと思われます。
![image](https://user-images.githubusercontent.com/17699481/78007318-1e9c0580-7379-11ea-94e0-1d69247abf99.png)

**Comment by nandenjin** [comment]
@asagatto777

**Comment by nandenjin** [comment]
フロント担当から❤️もらえたので実装OKで良いと思います。現状優先順位は低そうですが、どなたか手が空いていれば着手して問題ありません 🙆‍♂  Cc: @asagatto777

**Comment by mkobayashime** [comment]
僕やりますね。アサインお願いします。
