### ISSUE TITLE
Contribution時のupstream反映手順の修正？

### ISSUE THREAD

**Issue by nandenjin** [tsukuba-shinkan/shinkan-web#6]
https://github.com/tsukuba-shinkan/shinkan-web/blame/master/CONTRIBUTING.md#L29

> upstreamに変更が加えられた場合は以下のようにしてローカルに変更を反映させてください。（毎作業ごとに行うことを推奨します。）

これ、upstreamに変更がある際、作業ブランチに毎回取り込むべきだというふうに読めますが、多分作業ブランチを切る前に取り込んだ後は、PRを送るまではそのままでいいように思われます。（修正の必要ありますか？）

（また、そもそも作業ブランチを切る手順も書いてないので、これくらい丁寧に書いてあげるならついでに切り方も書いてあげたほうがいいような気がしました！手順は個人の好みなのでなくてもいいかもですけど）

**Comment by AsagaKosho** [comment]
#21 にて対応しました。
