### ISSUE TITLE
リセットCSSの入れ替え

### ISSUE THREAD

**Issue by mkobayashime** [tsukuba-shinkan/shinkan-web#61]
現状テンプレートデフォルトの`layout.scss`がリセットCSS的な働きをしていますが、#51 で言及の通り`font-family`をオーバーライドするなど問題が多いため、一般に提供されている別のメジャーなリセットCSSに入れ替えるのが良いかと思います。

導入するリセットCSSですが、余白のリセット思想やモバイルに対応していることなどを考慮し [sanitize.css](https://csstools.github.io/sanitize.css/) が良いのではないかと思います。問題なければ導入しますので、アサインしていただいて構いません。他のリセットCSSのほうが良いなどあればご提案ください。

**Comment by nandenjin** [comment]
@asagatto777

**Comment by AsagaKosho** [comment]
@mkobayashime 
対応遅くなり申し訳ございません。Assignさせていただきました。よろしくお願いいたします。
