### ISSUE TITLE
スプレッドシート画像のバッチ処理

### ISSUE THREAD

**Issue by yuki-js** [tsukuba-shinkan/shinkan-web#62]
現状アップされた画像は全てGdriveからホストされているが、本番環境でGoogleに頼りきりなのもどうなのか。
ということでインポートしてS3あたりに放り込むスクリプトを作った方がいいと思います。

**Comment by tkkrr** [comment]
- https://github.com/sondrele/gatsby-source-google-spreadsheet/issues/2
- https://github.com/gatsbyjs/gatsby/issues/14880

これらのissueを確認すると， gatsby-source-google-spreadsheet 単体では画像をホストできないため， [gatsby-plugin-remote-images](https://www.gatsbyjs.org/packages/gatsby-plugin-remote-images/)を使うといいみたいです．

**Comment by yuki-js** [comment]
gatsby-plugin-remote-imagesを使えばGoogle driveから直接インポートできるみたいですね。これを使う方針で行きますのでクローズします。

**Comment by tkkrr** [comment]
ちなみに，[こちら](https://jmolivas.com/how-use-google-spreadsheet-manage-content-and-trigger-deployment-your-gatsbyjs-site) に書いてあるように，Sharpを使えば[gatsby-plugin-remote-images](https://www.gatsbyjs.org/packages/gatsby-plugin-remote-images/?=remote)を使わなくとも最適化できるみたいです（手元で試していないため，なんとも言えませんが）．

参考までに

**Comment by yuki-js** [comment]
アク禁食らいました

**Comment by yuki-js** [comment]
案の定、かわかりませんがGoogleからアク禁食らいました。
開発用には必要だと思います…

**Comment by nandenjin** [comment]
設計段階では`gatsby-plugin-remote-images`を使う想定でいました。

@yuki-js 

> アク禁食らいました

とは具体的にどういう状態なのか詳しく載せていただけますか？

**Comment by tkkrr** [comment]
https://qiita.com/TechnoKuRo/items/622c3dcc2ff3f7e09474
いろいろ試してみてうまくいった時とうまくいかなかった時があったので，探してみたらこちらの記事にたどり着きました．

- spread sheetに記述されているURLを踏むと，その画像のキャッシュが生成され，元々のURLからキャッシュのURLへリダイレクトされる．
- キャッシュのURLへのリダイレクト時に何かしらのアクセストークンが付与されている？
- クリーンビルドすると，リダイレクト先へのアクセストークンを持っていないのでforbiddenになる．

そのため，
- buildがたまにうまくいく．
- 間を置かないクリーンビルドがうまくいかない
- 再buildで画像が表示されなくなる
- しばらく時間を置いてからbuildするとうまくいく

といった症状が発生するのだと考えられます．
Googleからのアクセス拒否はこんな感じで起きているので，
最初のissueにあったように別のソースにするのが良さそうです．

**Comment by tkkrr** [comment]
https://groups.google.com/forum/#!topic/google-apps-api-japan/Q7IZ_z6AfWY
こんなのもありました．
Google Drive API をちゃんと経由してアクセスすれば問題なくできそうです．
10,000,000 リクエスト数/日 まで叩ける（[ソース](https://qiita.com/minodisk/items/934903a937813fcf1e30)）ので，キャバは余裕そう

**Comment by nandenjin** [comment]
@tkkrr すみませんちょっと動作の仕組みを把握しきっていない気がし始めたので、2点質問させてください……:pray:

* `gatsby-plugin-remote-images` はリダイレクト先のコンテンツをローカルに保存しているのではなく、URLを保持して埋め込んでいるのですか？
* 上記の挙動は`build`と`develop`で変化する性質のものですか？

**Comment by yuki-js** [comment]
おはようございます

gatsby-plugin-remote-imageを使えば、URLに対応する画像オブジェクトを作れます。その時にURLの先を読み込みますが、その際Google Driveにリクエストを発行しすぎたため403エラーしか帰ってこなくなりました。セッションクッキーがなければ2回ビルドする余裕はないです。
それで、さっきまで時間つぶしに寝てました。

**Comment by tkkrr** [comment]
@nandenjin 連続の投稿，失礼しました．少し調査した結果を述べます．

> gatsby-plugin-remote-images はリダイレクト先のコンテンツをローカルに保存しているのではなく、URLを保持して埋め込んでいるのですか

ローカルに保存しているかどうか，私にはわかりませんでした．
Gatsbyの性質上，buildの生成物には画像が埋め込まれているものであると思いますが，手元でgatsby-plugin-remote-imagesを用いてうまく動作しなかったので別の方法から「Googleからアクセス禁止を受けた」原因を探そうと思いました．

ちなみに，gatsby-plugin-remote-imagesのREADMEにあるように，1つのノードに複数の画像がある場合には対応していないので，gatsby-plugin-remote-imagesを使って複数枚のビラを表示したいといった要件を満たすことは難しいかと考えられます．
https://github.com/graysonhicks/gatsby-plugin-remote-images#note-arrays-of-image-urls-at-leaf-nodes-are-currently-not-supported

第2の案として，gatsby-source-filesystem の createRemoteFileNode() を用いた実装を試みました．
実際に書いたコードは以下の通りです．

```javascript
const { createRemoteFileNode } = require(`gatsby-source-filesystem`)

exports.sourceNodes = async (
  { actions, cache, store, createNodeId, createContentDigest },
  options
) => {

 /// 中略 /// 
for( ... ){

await (async () => {
    const url = `${splitArrayString(row[12])[0]}&export=view&usp=sharing`
    let fileNode = null
    // createRemoteFileNodeで外部の画像のファイルノードを作成する
    try {
        fileNode = await createRemoteFileNode({
            url: url,
            cache,
            store,
            createNode: actions.createNode,
            createNodeId: createNodeId,
        })

        // 他ファイルノードと区別するための識別子
        await actions.createNodeField({
            node: fileNode,
            name: `DriveImages`,
            value: `true`,
        })
        // どこの団体の画像であるか
        await actions.createNodeField({
            node: fileNode,
            name: `organizationPrimaryKey`,
            value: row[0],
        })
    } catch (e) {
        console.log(e)
    }
    return fileNode
})()

}

}

```

このコードは最初は問題なくbuildでき，Sharpの恩恵を得ることができました．
しかし，別のライブラリも試してみようと`npm start`を一度停止し，再度`npm start`した時，画像が表示されなくなり，先述したような問題が発生しました．


> 上記の挙動はbuildとdevelopで変化する性質のものですか？

どちらでも同様の問題があるみたいです．
![スクリーンショット 2020-04-01 18 50 07](https://user-images.githubusercontent.com/36618448/78123802-b79a5180-7449-11ea-8d8d-d0b828dda78c.png)

**Comment by yuki-js** [comment]
一回のビルドあたり数十HTTPリクエストがGoogleに対して送られるので、
2回ビルドすると100件近く送ることになります。そうするとGoogleは通信を遮断します。
なので、私も1回しかビルドできず、寝て制限解除を待っていたわけです。

**Comment by yuki-js** [comment]
なお、 #18 は私がアサインされています

**Comment by nandenjin** [comment]
@tkkrr わざわざお手間おかけしてすみません、ありがとうございます。大変助かりました……！

**Comment by nandenjin** [comment]
@yuki-js 

> 2回ビルドすると100件近く送ることになります。そうするとGoogleは通信を遮断します。

参考までになのですが、これについてソースとなるドキュメントなどはありますか？Aokiさんの環境での結果をベースにした推定でしょうか？:thinking:

**Comment by tkkrr** [comment]
@nandenjin いえいえ，こちらこそ応援しています．
@yuki-js すみません．配慮が足りませんでした．こちらが余計なHTTPリクエストを送らないように，他の部分の調査を進めたいと思います．

**Comment by nandenjin** [comment]
本件について、少しOwnerと相談して今後の対処を決めたいと思いますのでお待ちください。このIssue自体が #18 の流れの下にあるので、こちらはいったんCloseし、#18 の方で報告します:bow: 

（個人的には余計な実装の手間をかけてまでGoogle Driveを使うほどのメリットはないと感じるので、何か代替のストレージを検討したいと思います）

Cc: @asagatto777
