### ISSUE TITLE
トップページUIの再実装

### ISSUE THREAD

**Issue by nandenjin** [tsukuba-shinkan/shinkan-web#63]
#42 を受けての実装です。

* 横スクロールを禁止する
* ホバー/タップアクションでの団体名表示
* 表示フィルタの実装

（フィルタのUIがありませんが https://github.com/tsukuba-shinkan/shinkan-web/issues/42#issuecomment-606376844 のプランCのような形を予定しています）

![トップページPC（稲田試験版-ホバー縦型）](https://user-images.githubusercontent.com/7803255/78112710-916cb580-7439-11ea-82a7-a2b5cbbc57c1.png)

![トップページSP（稲田試験版-タップで展開）](https://user-images.githubusercontent.com/7803255/78112698-8d409800-7439-11ea-9d43-faea47bc8341.png)

**Comment by mkobayashime** [comment]
@nandenjin 本件でかなりスタイルを記述されると思うのですが、仮に #65 がマージされるとリセットCSSの切り替えに伴うスタイル崩れが発生する可能性がある(詳しくは #65 を御覧ください)ので、マージされたら可能な限り早めにローカルに引っ張っていただいて、スタイル崩れがあれば修正していただければと思います。

**Comment by tkkrr** [comment]
@nandenjin @mkobayashime デザインおつかれさまです．
これから書くことは個人の一意見として読み流してくれればと思います．

新歓の良さはみんなが楽しそうに無差別にゴチャっとした勧誘してくれる意味わからん感覚だと個人的に思ってます（あくまで **個人的に** です）．新入生がその時に考えるのはこの団体はどういう団体なんだろうとかよりも先に「楽しい」とか「新生活を歓迎されている感」なんだろうなと思います．
これを踏まえて

> - 横スクロールを禁止する

あえて横に自動スクロールさせることでゴチャっと感を出すとか（実装は面倒くさそうですが）
このまま進むにしても画像をひとまわり多く敷き詰めて密度を上げるとかするとゴチャゴチャして楽しいのかなと

> - ホバー/タップアクションでの団体名表示

気になるならクリックして詳細を見る or 検索する と思うのでそこまで親切な実装はしなくていいのかなと．せめてscaleしてクリックできますよ感を出すだけにするとか（密度が高ければ高いほどたくさんの画像がもりもり大小するのでそれはそれで楽しそうです）

> - 表示フィルタの実装

これはトップページより検索UIに欲しいかもですね
トップページは [ 気になるサークルを検索 🔍] などを表示して検索UIへの移行をシームレスにすると楽しい気分のまま検索できそうですね


こんな感じで，せっかくの新歓の代わりなので，楽しいUIがあったらいいなぁと思ってます．

**Comment by tkkrr** [comment]
https://github.com/tsukuba-shinkan/shinkan-web/issues/63#issuecomment-607321732
ここじゃなくて #42 に書くべき内容だと思ったので，邪魔そうなら上記コメント移動します．

**Comment by nandenjin** [comment]
実装やってますが予想以上にスマホ版の文字サイズが厳しくて、これ本当に使い物になるのかという感じですね……どうなることやら……

![IMG_4569](https://user-images.githubusercontent.com/7803255/78266334-9f592e00-7540-11ea-8a31-355444e2bf1f.JPG)

**Comment by mkobayashime** [comment]
やっぱりスマホだと文字サイズキツイですよね…まあサイトの性質上若年層以外のユーザーをほぼ考慮しなくて良いのでなんとか…

**Comment by yuki-js** [comment]
スマホデザインですが、先日私が作り直したブログのデザインは参考になりませんかね。
https://blog.mynumber.dev/
