### ISSUE TITLE
フッター内リンクのテキスト色コントラスト確保

### ISSUE THREAD

**Issue by mkobayashime** [tsukuba-shinkan/shinkan-web#70]
フッター内に`about`ページリンクなど2つのリンクが存在しますが、(画像参照)
![image](https://user-images.githubusercontent.com/17699481/78158133-d4e81380-747b-11ea-9615-c7ec4865f92f.png)

背景色とテキスト色のコントラストが非常に低く、WCAG基準を全くクリアしていません。
![image](https://user-images.githubusercontent.com/17699481/78158346-137dce00-747c-11ea-88fa-2199ab59c5c8.png)

ということで、テキスト色自体は通常のテキスト色である黒(or濃いグレー)にした上で、リンクであることがわかるよう下線を付けることを提案します。

**Comment by AsagaKosho** [comment]
![image](https://user-images.githubusercontent.com/17997951/78196827-8f006f00-74be-11ea-951c-51f59d6afbfc.png)
@mkobayashime 
#6600cc ではどうでしょう？
（ちなみに、もともと設定していた水色は筑波大の準ブランドカラーである「フューチャーブルー」、 #6600cc はブランドカラーである「つくば紫」です。

**Comment by mkobayashime** [comment]
@asagatto777
非常に良いですね。
それなら、ユーザーを混乱させないようページ内の全てのリンクをつくば紫にするべきかと思いますが、いかがですか?
今 @nandenjin さんが #63 の実装にあたって色変数を定義しているのではないかと思うので、実際の実装はそのマージを待ってからにしましょう。

**Comment by nandenjin** [comment]
> 今 @nandenjin さんが #63 の実装にあたって色変数を定義しているのではないかと思うので、実際の実装はそのマージを待ってからにしましょう。

#73 でレビュー待ちをしていますが、メディアクエリと #73 で使う変数だけ定義したので、マージされたら値の追加等お願いします！

**Comment by mkobayashime** [comment]
@nandenjin 承知しました。ありがとうございます!

**Comment by mkobayashime** [comment]
@nandenjin 若干本 Issue から逸れますが、 #73 により `main` の背景色が `#eeeeee`となったことでフッター(背景色 `#eaeaea`)との境界がほぼ見えなくなってしまったので、フッターをヘッダーと同じ `#ffffff` にしませんか?
背景が `#ffffff` であっても WCAG クリアしていないので、いずれにせよリンク色はつくば紫に変更しようと思います。

**Comment by AsagaKosho** [comment]
@mkobayashime 
フッター色の変更、良いと思います！
