### ISSUE TITLE
otherImageがないと表示が崩れる

### ISSUE THREAD

**Issue by yuki-js** [tsukuba-shinkan/shinkan-web#71]
otherImageがない投稿は崩れます。直し方・やってくれる人募集

![image](https://user-images.githubusercontent.com/20838151/78204147-c594b480-74d3-11ea-9622-0c0ad70e2ab2.png)

**Comment by HikaruEgashira** [comment]
個別ページは #53 でプロトタイプ作成後に着手されるので、それと同時に修正しましょう

**Comment by AsagaKosho** [comment]
#69 で修正できているものと思われます（当該プルリクはレビュー待ち）

**Comment by yuki-js** [comment]
ではそれらのissueの解決に任せることにします。
