### ISSUE TITLE
フッターのレイアウトの修正

### ISSUE THREAD

**Issue by nawta** [tsukuba-shinkan/shinkan-web#72]
細かいことなんですけど、
フッターのここから筑波大公式HPに飛ぶようにしたら良さげな気もします。どうですかね？
<img width="1082" alt="スクリーンショット 2020-04-03 11 12 51" src="https://user-images.githubusercontent.com/39507181/78317116-5f279900-759c-11ea-9506-80b2d67dcfe3.png">

あと、著作権のところなんですけど
https://nandemo-nobiru.com/om-6265
こういうサイトとか見る感じではサイト公開の年を年代のところに入れることが多いっぽいです。なのでnew Date.getYear()を使って最新の年代を取得せずに2020でいい気もします。

イメージ的には
これが
<img width="717" alt="スクリーンショット 2020-04-03 11 25 50" src="https://user-images.githubusercontent.com/39507181/78318343-73b96080-759f-11ea-8367-49c6ad445d2a.png">

こうなる感じです。
<img width="713" alt="スクリーンショット 2020-04-03 11 32 17" src="https://user-images.githubusercontent.com/39507181/78318335-70be7000-759f-11ea-99cc-eaed02246a53.png">

**Comment by yuki-js** [comment]
筑波大学アイコンが今Google Driveからホストされてますが、ついでに本リポジトリに取り込んだ方がいいと思います。
