### ISSUE TITLE
DOMにkey propを付け足す

### ISSUE THREAD

**Issue by nawta** [tsukuba-shinkan/shinkan-web#76]
アクセスが重くなりそうなら、再レンダリングの効率化はかるべき…？
http://blog.aqutras.com/entry/2016/06/23/210000
いや、keyなんぞいらんわ！ってなったら意見ください。(真面目にReactはチュートリアル回した事あるくらい&stdのサーバがどんな物か把握が甘いので何ともいえない)

DevToolにwarningめっちゃ出る。
<img width="1436" alt="スクリーンショット 2020-04-03 10 57 44" src="https://user-images.githubusercontent.com/39507181/78322946-3ce94780-75ab-11ea-9587-9dd184670c6c.png">

**Comment by nandenjin** [comment]
あ、これ #75 でLint通らないようにして、既存のところは修正したはずです。マージされたら治ると思うんですが、もし治ってなかったらReopenしてください。ありがとうございます:pray:
