### ISSUE TITLE
トップページhoverのモーダルでフッターリンクが押せない

### ISSUE THREAD

**Issue by mkobayashime** [tsukuba-shinkan/shinkan-web#78]
#73 のレビュー時に気づいていなかったのですが、トップページでサークル詳細情報を表示するモーダルについて、モーダル全域がhover対象となっていることで

以下の画像の`このサイトについて`付近にカーソルを移動させると
![image](https://user-images.githubusercontent.com/17699481/78355631-f9adc980-75e8-11ea-9d6b-ca8e7a89edd9.png)
このように上のサークルのモーダルが展開してしまい、`このサイトについて`がクリック不能となっています。
![image](https://user-images.githubusercontent.com/17699481/78355676-10ecb700-75e9-11ea-97e8-1a73292230af.png)

対処として、hoverの対象範囲をポスター画像のみに狭めるまたはフッター上の`margin`を広げる
ことを提案します。

**Comment by nandenjin** [comment]
あーーごめんなさい……他のポスターは上のモーダルよりも前面に来る（ホバー時だけ`z-index`で表に出る）ことでこの現象を防いでるので、なぜフッターではこれが効かなかったのかって感じです……

申し訳ないのですが今稲田がこれに手をつける余裕がないので、どなたか担当していただけるか、応急処置でもマージンをとるかしていただけるとありがたいです。稲田が手をつけられるようになったら手をつけるので、誰も取れない場合はほっといていただければと思います🙏

**Comment by mkobayashime** [comment]
とりあえず原因調査中です…

**Comment by tkkrr** [comment]
分かったことを共有しておきます．
z-indexは各`position:`でスタックが作られているみたいです．
現在，.org-list__itemが`position: relative`，.org-list__item__posterの方は`position: absolute`，footerは`position: static`となっています．
そのため，.org-list__item以下を`position: static`にする，もしくはfooterを`position: absolute`にすると想定通りのz-indexが動作するということになります．

対策として前者の方はレイアウトが大きく崩れるので避けるとして，
後者の方を採用した動作が以下のようになります

![output](https://user-images.githubusercontent.com/36618448/78385641-2547a880-7617-11ea-8718-014280a39cf1.gif)

なお，footerが`position: absolute`になってしまうという課題はあります．
@nandenjin もしよろしければプルリクたてます．

**Comment by mkobayashime** [comment]
footerは`position: static;`のまま非ホバー時の`.org-list__item__poster`とその中の`img`の`height`を`figcaption`分減らすことでも解決できたんですが、 @tkkrr さんの実装の方が定石でしょうし`position: absolute;`にそこまでデメリットがあるとは思えないので、そちらで良さそうです。

**Comment by nandenjin** [comment]
お二人ともありがとうございます！トップページ固有のUIがグローバルな要素に影響を与えてるのが微妙に気になるところではありますが、実装として早そうなのでひとまず @tkkrr さんのテストしている形でPRお願いしても良いでしょうか……？:pray:

**Comment by tkkrr** [comment]
@nandenjin わかりました．プルリクたてます．
