### ISSUE TITLE
大学ロゴをローカルにおく

### ISSUE THREAD

**Issue by AsagaKosho** [tsukuba-shinkan/shinkan-web#80]
現在Google Driveからのホストになっている

**Comment by nawta** [comment]
https://takumon.com/simple-gatsby-image-wrapper

この辺を使うと良さげ？

**Comment by tkkrr** [comment]
`gatsby-source-filesystem`を使っているので，Google Driveにある画像を`src/images/`に保存すれば，gatsbyのGraphQLから参照できてかつgatsby-imageによる最適化ができます．

これはheaderの画像も同様ですね．

**Comment by AsagaKosho** [comment]
@nawta @tkkrr 
ありがとうございます！
