### ISSUE TITLE
個別ページUI設計

### ISSUE THREAD

**Issue by AsagaKosho** [tsukuba-shinkan/shinkan-web#9]

**Comment by nandenjin** [comment]
#14 ありがとうございます 🙋‍♂
実装側的にはどこかに最終形のデザイン公開されてると作るとこわかりやすくていいのですが 🤔

**Comment by nandenjin** [comment]
@asagatto777 実装は切り分けて別Issueでも良いと思うので設計の完成系だけどっかにお願いします 🙏 （ #20 でデザイン案が見れるようになるならそれで解決でも良いと思います）
