### ISSUE TITLE
画像の端が収まりきっていない

### ISSUE THREAD

**Issue by AsagaKosho** [tsukuba-shinkan/shinkan-web#91]
ポスター画像の端が切れている
![image](https://user-images.githubusercontent.com/17997951/78470819-343d7080-7767-11ea-9be2-c80ff6743a5e.png)

**Comment by mkobayashime** [comment]
@asagatto777 手元の Chrome/Firefox/Edge のいずれでも再現しないんですが、ブラウザ何をお使いですか?

**Comment by AsagaKosho** [comment]
@mkobayashime 
Chrome（Ver.80.0, Win10）です.
Edge 80.0, Firefox 74.0 でも再現しました

**Comment by mkobayashime** [comment]
@asagatto777 よく見たらローカルのソース upstream から遅れてたので merge して再確認します。お騒がせしました。

**Comment by AsagaKosho** [comment]
参考） 備忘録です

gatsby-imageの仕様
 - fluidではmaxWidth, maxHeight を指定して、可変サイズ（（指定範囲内で）親要素いっぱいまで広がる）
 - fixedではwidth, height を指定して固定サイズ 

現状、トップページのポスター画像にはfixedでwidthに200pxが指定されている。
しかし囲っているli要素の幅が188.45pxであるため、はみ出したぶんが表示できていない状態

fluidにすれば解決するのかというと、そう単純な話ではない


次のような構成になっている

![image](https://user-images.githubusercontent.com/17997951/78503241-61f2db80-77a0-11ea-84d4-41e9abee481f.png)

親要素から順に領域の画像を貼り付ける

![image](https://user-images.githubusercontent.com/17997951/78503181-00cb0800-77a0-11ea-95fb-4b82a93b09a4.png)

![image](https://user-images.githubusercontent.com/17997951/78503194-19d3b900-77a0-11ea-9d85-3f3e7e220f25.png)

![image](https://user-images.githubusercontent.com/17997951/78503206-23f5b780-77a0-11ea-807f-0814e37999a0.png)

![image](https://user-images.githubusercontent.com/17997951/78503234-57d0dd00-77a0-11ea-8ef0-fd3eb63b3a2a.png)

div.gatsby-image-wrapperの直接の親要素がfigureになっているためfluidにするとfigure要素に合わさり、はみ出てしまう

**Comment by AsagaKosho** [comment]
解決策わかりました。対応します。

fluidでmaxWidth: 200 にした上で、
imgにかかっているmargin:15px;を取り除き、div.gatsby-image-wrapperにmargin:15px;をつける
