### ISSUE TITLE
モバイルで画像の端が重なってしまう

### ISSUE THREAD

**Issue by AsagaKosho** [tsukuba-shinkan/shinkan-web#92]
![image](https://user-images.githubusercontent.com/17997951/78472311-ab2c3680-7772-11ea-9766-4e694372f0c4.png)

**Comment by AsagaKosho** [comment]
表示崩れも確認。
liよりも画像が大きくなってる
![image](https://user-images.githubusercontent.com/17997951/78472367-1118be00-7773-11ea-8856-702dadf47339.png)

**Comment by AsagaKosho** [comment]
@yuki-js @nandenjin 
#91 含め対応策お願いします。

**Comment by asagatto777** [comment]
&nbsp;

**Comment by asagatto777** [comment]
#91

**Comment by AsagaKosho** [comment]
#91 の対応で解決しそうです。
